### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by FChataigner** [dataiku/dataiku-api-client-python#20]
at least iter_rows() on sql_query and dataset fail

**Comment by victorjourne** [comment]
I confirm, on a dataikuapi.dss.dataset.DSSDataset object,  iter_rows() fails:
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-58-912e50a7fcba> in <module>
      2 print(columns)
      3 row_count = 0
----> 4 for row in dataset.iter_rows():
      5         print(row)
      6         row_count = row_count + 1

/opt/conda/lib/python3.6/site-packages/dataikuapi/utils.py in iter_rows(self)
     83                                          delimiter='\t',
     84                                          quotechar='"',
---> 85                                          doublequote=True):
     86                 yield [none_if_throws(caster)(val)
     87                        for (caster, val) in dku_zip_longest(casters, uncasted_tuple)]

Error: iterator should return strings, not bytes (did you open the file in text mode?)
---------------------------------------------------------------------------
Config: 
- dataiku-api-client 4.3.0
- Python 3.6

**Comment by victorjourne** [comment]
@FChataigner, did you install the package with pip?
install the latest version of dataikuapi with the setup.py, works now for me!

**Comment by bandaangosta** [comment]
This was fixed with pull request #33, although it appears it has not reached pypi yet.
In the meantime, you can install latest version directly from this repository:

`pip install git+https://github.com/dataiku/dataiku-api-client-python@master#egg=dataiku-api-client`

**Comment by ankurc9** [comment]
@bandaangosta, Thank you so much for the solution. It worked for me. However installing the latest version still does not resolve the problem.
